INSERT INTO [cities]([id], [name]) VALUES (1, N'Adana'); GO
INSERT INTO [cities]([id], [name]) VALUES (2, N'Adıyaman'); GO
INSERT INTO [cities]([id], [name]) VALUES (3, N'Afyonkarahisar'); GO
INSERT INTO [cities]([id], [name]) VALUES (4, N'Ağrı'); GO
INSERT INTO [cities]([id], [name]) VALUES (5, N'Amasya'); GO
INSERT INTO [cities]([id], [name]) VALUES (6, N'Ankara'); GO
INSERT INTO [cities]([id], [name]) VALUES (7, N'Antalya'); GO
INSERT INTO [cities]([id], [name]) VALUES (8, N'Artvin'); GO
INSERT INTO [cities]([id], [name]) VALUES (9, N'Aydın'); GO
INSERT INTO [cities]([id], [name]) VALUES (10, N'Balıkesir'); GO
INSERT INTO [cities]([id], [name]) VALUES (11, N'Bilecik'); GO
INSERT INTO [cities]([id], [name]) VALUES (12, N'Bingöl'); GO
INSERT INTO [cities]([id], [name]) VALUES (13, N'Bitlis'); GO
INSERT INTO [cities]([id], [name]) VALUES (14, N'Bolu'); GO
INSERT INTO [cities]([id], [name]) VALUES (15, N'Burdur'); GO
INSERT INTO [cities]([id], [name]) VALUES (16, N'Bursa'); GO
INSERT INTO [cities]([id], [name]) VALUES (17, N'Çanakkale'); GO
INSERT INTO [cities]([id], [name]) VALUES (18, N'Çankırı'); GO
INSERT INTO [cities]([id], [name]) VALUES (19, N'Çorum'); GO
INSERT INTO [cities]([id], [name]) VALUES (20, N'Denizli'); GO
INSERT INTO [cities]([id], [name]) VALUES (21, N'Diyarbakır'); GO
INSERT INTO [cities]([id], [name]) VALUES (22, N'Edirne'); GO
INSERT INTO [cities]([id], [name]) VALUES (23, N'Elazığ'); GO
INSERT INTO [cities]([id], [name]) VALUES (24, N'Erzincan'); GO
INSERT INTO [cities]([id], [name]) VALUES (25, N'Erzurum'); GO
INSERT INTO [cities]([id], [name]) VALUES (26, N'Eskişehir'); GO
INSERT INTO [cities]([id], [name]) VALUES (27, N'Gaziantep'); GO
INSERT INTO [cities]([id], [name]) VALUES (28, N'Giresun'); GO
INSERT INTO [cities]([id], [name]) VALUES (29, N'Gümüşhane'); GO
INSERT INTO [cities]([id], [name]) VALUES (30, N'Hakkari'); GO
INSERT INTO [cities]([id], [name]) VALUES (31, N'Hatay'); GO
INSERT INTO [cities]([id], [name]) VALUES (32, N'Isparta'); GO
INSERT INTO [cities]([id], [name]) VALUES (33, N'Mersin'); GO
INSERT INTO [cities]([id], [name]) VALUES (34, N'İstanbul'); GO
INSERT INTO [cities]([id], [name]) VALUES (35, N'İzmir'); GO
INSERT INTO [cities]([id], [name]) VALUES (36, N'Kars'); GO
INSERT INTO [cities]([id], [name]) VALUES (37, N'Kastamonu'); GO
INSERT INTO [cities]([id], [name]) VALUES (38, N'Kayseri'); GO
INSERT INTO [cities]([id], [name]) VALUES (39, N'Kırklareli'); GO
INSERT INTO [cities]([id], [name]) VALUES (40, N'Kırşehir'); GO
INSERT INTO [cities]([id], [name]) VALUES (41, N'Kocaeli'); GO
INSERT INTO [cities]([id], [name]) VALUES (42, N'Konya'); GO
INSERT INTO [cities]([id], [name]) VALUES (43, N'Kütahya'); GO
INSERT INTO [cities]([id], [name]) VALUES (44, N'Malatya'); GO
INSERT INTO [cities]([id], [name]) VALUES (45, N'Manisa'); GO
INSERT INTO [cities]([id], [name]) VALUES (46, N'Kahramanmaraş'); GO
INSERT INTO [cities]([id], [name]) VALUES (47, N'Mardin'); GO
INSERT INTO [cities]([id], [name]) VALUES (48, N'Muğla'); GO
INSERT INTO [cities]([id], [name]) VALUES (49, N'Muş'); GO
INSERT INTO [cities]([id], [name]) VALUES (50, N'Nevşehir'); GO
INSERT INTO [cities]([id], [name]) VALUES (51, N'Niğde'); GO
INSERT INTO [cities]([id], [name]) VALUES (52, N'Ordu'); GO
INSERT INTO [cities]([id], [name]) VALUES (53, N'Rize'); GO
INSERT INTO [cities]([id], [name]) VALUES (54, N'Sakarya'); GO
INSERT INTO [cities]([id], [name]) VALUES (55, N'Samsun'); GO
INSERT INTO [cities]([id], [name]) VALUES (56, N'Siirt'); GO
INSERT INTO [cities]([id], [name]) VALUES (57, N'Sinop'); GO
INSERT INTO [cities]([id], [name]) VALUES (58, N'Sivas'); GO
INSERT INTO [cities]([id], [name]) VALUES (59, N'Tekirdağ'); GO
INSERT INTO [cities]([id], [name]) VALUES (60, N'Tokat'); GO
INSERT INTO [cities]([id], [name]) VALUES (61, N'Trabzon'); GO
INSERT INTO [cities]([id], [name]) VALUES (62, N'Tunceli'); GO
INSERT INTO [cities]([id], [name]) VALUES (63, N'Şanlıurfa'); GO
INSERT INTO [cities]([id], [name]) VALUES (64, N'Uşak'); GO
INSERT INTO [cities]([id], [name]) VALUES (65, N'Van'); GO
INSERT INTO [cities]([id], [name]) VALUES (66, N'Yozgat'); GO
INSERT INTO [cities]([id], [name]) VALUES (67, N'Zonguldak'); GO
INSERT INTO [cities]([id], [name]) VALUES (68, N'Aksaray'); GO
INSERT INTO [cities]([id], [name]) VALUES (69, N'Bayburt'); GO
INSERT INTO [cities]([id], [name]) VALUES (70, N'Karaman'); GO
INSERT INTO [cities]([id], [name]) VALUES (71, N'Kırıkkale'); GO
INSERT INTO [cities]([id], [name]) VALUES (72, N'Batman'); GO
INSERT INTO [cities]([id], [name]) VALUES (73, N'Şırnak'); GO
INSERT INTO [cities]([id], [name]) VALUES (74, N'Bartın'); GO
INSERT INTO [cities]([id], [name]) VALUES (75, N'Ardahan'); GO
INSERT INTO [cities]([id], [name]) VALUES (76, N'Iğdır'); GO
INSERT INTO [cities]([id], [name]) VALUES (77, N'Yalova'); GO
INSERT INTO [cities]([id], [name]) VALUES (78, N'Karabük'); GO
INSERT INTO [cities]([id], [name]) VALUES (79, N'Kilis'); GO
INSERT INTO [cities]([id], [name]) VALUES (80, N'Osmaniye'); GO
INSERT INTO [cities]([id], [name]) VALUES (81, N'Düzce'); GO
